/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author joshtin_mac
 */
public class PanelConvolucion extends javax.swing.JPanel {

    /**
     * Creates new form PanelConvolucion
     */
    public PanelConvolucion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        posicion1 = new javax.swing.JTextField();
        posicion2 = new javax.swing.JTextField();
        posicion3 = new javax.swing.JTextField();
        posicion4 = new javax.swing.JTextField();
        posicion5 = new javax.swing.JTextField();
        posicion6 = new javax.swing.JTextField();
        posicion7 = new javax.swing.JTextField();
        posicion8 = new javax.swing.JTextField();
        posicion9 = new javax.swing.JTextField();
        buttonAplicar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Convolución"));

        jLabel1.setFont(new java.awt.Font("Kailasa", 1, 14)); // NOI18N
        jLabel1.setText("Ingresa la matriz:");

        posicion1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        posicion1.setPreferredSize(new java.awt.Dimension(50, 50));
        posicion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicion1ActionPerformed(evt);
            }
        });

        posicion2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        posicion2.setPreferredSize(new java.awt.Dimension(50, 50));
        posicion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicion2ActionPerformed(evt);
            }
        });

        posicion3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        posicion3.setPreferredSize(new java.awt.Dimension(50, 50));
        posicion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicion3ActionPerformed(evt);
            }
        });

        posicion4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        posicion4.setPreferredSize(new java.awt.Dimension(50, 50));
        posicion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicion4ActionPerformed(evt);
            }
        });

        posicion5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        posicion5.setPreferredSize(new java.awt.Dimension(50, 50));
        posicion5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicion5ActionPerformed(evt);
            }
        });

        posicion6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        posicion6.setPreferredSize(new java.awt.Dimension(50, 50));
        posicion6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicion6ActionPerformed(evt);
            }
        });

        posicion7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        posicion7.setPreferredSize(new java.awt.Dimension(50, 50));
        posicion7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicion7ActionPerformed(evt);
            }
        });

        posicion8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        posicion8.setPreferredSize(new java.awt.Dimension(50, 50));
        posicion8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicion8ActionPerformed(evt);
            }
        });

        posicion9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        posicion9.setPreferredSize(new java.awt.Dimension(50, 50));
        posicion9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicion9ActionPerformed(evt);
            }
        });

        buttonAplicar.setText("Aplicar filtro");
        buttonAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAplicarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(posicion4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(posicion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(posicion7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(posicion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(posicion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(posicion5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(posicion6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(posicion8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(posicion9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(buttonAplicar)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(posicion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(posicion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(posicion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(posicion4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(posicion5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(posicion6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(posicion7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(posicion8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(posicion9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonAplicar)
                .addGap(9, 9, 9))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void posicion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posicion1ActionPerformed

    private void posicion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posicion2ActionPerformed

    private void posicion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicion3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posicion3ActionPerformed

    private void posicion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicion4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posicion4ActionPerformed

    private void posicion5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicion5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posicion5ActionPerformed

    private void posicion6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicion6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posicion6ActionPerformed

    private void posicion7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicion7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posicion7ActionPerformed

    private void posicion8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicion8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posicion8ActionPerformed

    private void posicion9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicion9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posicion9ActionPerformed

    private void buttonAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAplicarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAplicarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton buttonAplicar;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JTextField posicion1;
    public javax.swing.JTextField posicion2;
    public javax.swing.JTextField posicion3;
    public javax.swing.JTextField posicion4;
    public javax.swing.JTextField posicion5;
    public javax.swing.JTextField posicion6;
    public javax.swing.JTextField posicion7;
    public javax.swing.JTextField posicion8;
    public javax.swing.JTextField posicion9;
    // End of variables declaration//GEN-END:variables
}
