package vista;

import controlador.ControladorAplicacion;
import java.awt.event.AdjustmentEvent;
import java.awt.event.AdjustmentListener;
import vista.PanelUmbralizacion;
/**
 *
 * @author antoniocuevas
 */
public class Principal extends javax.swing.JFrame {
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        new ControladorAplicacion(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        labelImagen = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemAbrir = new javax.swing.JMenuItem();
        jMenuGuardar = new javax.swing.JMenuItem();
        jMenuCreditos = new javax.swing.JMenuItem();
        menuOperaciones = new javax.swing.JMenu();
        menuItemEscalaGrises = new javax.swing.JMenuItem();
        menuItemRotar90 = new javax.swing.JMenuItem();
        menuItem180 = new javax.swing.JMenuItem();
        menuItem270 = new javax.swing.JMenuItem();
        menuItemTraslacion = new javax.swing.JMenuItem();
        menuItemSumaEscalar = new javax.swing.JMenuItem();
        menuItemRestaEscalar = new javax.swing.JMenuItem();
        menuItemReflexionX = new javax.swing.JMenuItem();
        menuItemReflexionY = new javax.swing.JMenuItem();
        menuItemSuma = new javax.swing.JMenuItem();
        menuItemResta = new javax.swing.JMenuItem();
        jMenuLogica = new javax.swing.JMenu();
        jMenuItemAnd = new javax.swing.JMenuItem();
        jMenuItemOr = new javax.swing.JMenuItem();
        jMenuItemNot = new javax.swing.JMenuItem();
        jMenuItemXor = new javax.swing.JMenuItem();
        menFil = new javax.swing.JMenu();
        menuItemUm = new javax.swing.JMenuItem();
        menuItemCon = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuAritmetica = new javax.swing.JMenuItem();
        jMenuMediaG = new javax.swing.JMenuItem();
        jMenuContra = new javax.swing.JMenuItem();
        jMenuItemMediana = new javax.swing.JMenuItem();
        jMenuMax = new javax.swing.JMenuItem();
        jMenuMinimo = new javax.swing.JMenuItem();
        jMenuMedio = new javax.swing.JMenuItem();
        jMenuAdaptativo = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuTransformar = new javax.swing.JMenuItem();
        jMenuEspectro = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuILPF = new javax.swing.JMenuItem();
        jMenuBLPF = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuIHPF = new javax.swing.JMenuItem();
        jMenuBHPF = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuIBPF = new javax.swing.JMenuItem();
        jMenuIBSF = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuBBPF = new javax.swing.JMenuItem();
        jMenuBBSF = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuCalcularHistograma = new javax.swing.JMenuItem();
        jMenuVerHistograma = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuRtoC = new javax.swing.JMenuItem();
        jMenuCtoR = new javax.swing.JMenuItem();
        jMenuRtoH = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jManuDilatacion = new javax.swing.JMenuItem();
        jMenuErosion = new javax.swing.JMenuItem();
        jMenuApertura = new javax.swing.JMenuItem();
        jMenuCierre = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemOriginal = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Configuración de imagen"));
        jPanel1.setName("panelEste"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Propiedades"));
        jPanel3.setPreferredSize(new java.awt.Dimension(380, 154));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Previsualización de imagen"));
        jPanel2.setPreferredSize(new java.awt.Dimension(506, 442));

        jScrollPane1.setViewportView(labelImagen);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        jMenu1.setText("Archivo");
        jMenu1.setName("menuArchivo"); // NOI18N

        menuItemAbrir.setBackground(new java.awt.Color(204, 204, 204));
        menuItemAbrir.setIcon(new javax.swing.ImageIcon("/Users/joshtin_pc/Documents/Imagenes para proyecto/icons/Disco.png")); // NOI18N
        menuItemAbrir.setText("Abrir Imagen");
        menuItemAbrir.setName("menuItemAbrir"); // NOI18N
        jMenu1.add(menuItemAbrir);

        jMenuGuardar.setIcon(new javax.swing.ImageIcon("/Users/joshtin_pc/Documents/Imagenes para proyecto/icons/Diskette.png")); // NOI18N
        jMenuGuardar.setText("Guardar imagen");
        jMenuGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGuardarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuGuardar);

        jMenuCreditos.setIcon(new javax.swing.ImageIcon("/Users/joshtin_pc/Documents/Imagenes para proyecto/icons/Estrella.png")); // NOI18N
        jMenuCreditos.setText("Creditos");
        jMenu1.add(jMenuCreditos);

        jMenuBar1.add(jMenu1);

        menuOperaciones.setText("Operaciones");

        menuItemEscalaGrises.setIcon(new javax.swing.ImageIcon("/Users/joshtin_pc/Documents/Imagenes para proyecto/icons/B:N.png")); // NOI18N
        menuItemEscalaGrises.setText("Escala Grises");
        menuOperaciones.add(menuItemEscalaGrises);

        menuItemRotar90.setIcon(new javax.swing.ImageIcon("/Users/joshtin_pc/Documents/Imagenes para proyecto/icons/90.png")); // NOI18N
        menuItemRotar90.setText("Rotar 90°");
        menuItemRotar90.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRotar90ActionPerformed(evt);
            }
        });
        menuOperaciones.add(menuItemRotar90);

        menuItem180.setIcon(new javax.swing.ImageIcon("/Users/joshtin_pc/Documents/Imagenes para proyecto/icons/180.png")); // NOI18N
        menuItem180.setText("Rotar 180°");
        menuOperaciones.add(menuItem180);

        menuItem270.setIcon(new javax.swing.ImageIcon("/Users/joshtin_pc/Documents/Imagenes para proyecto/icons/270.png")); // NOI18N
        menuItem270.setText("Rotar 270°");
        menuOperaciones.add(menuItem270);

        menuItemTraslacion.setIcon(new javax.swing.ImageIcon("/Users/joshtin_pc/Documents/Imagenes para proyecto/icons/traslacion.png")); // NOI18N
        menuItemTraslacion.setText("Traslacion");
        menuItemTraslacion.setToolTipText("");
        menuOperaciones.add(menuItemTraslacion);

        menuItemSumaEscalar.setIcon(new javax.swing.ImageIcon("/Users/joshtin_pc/Documents/Imagenes para proyecto/icons/suma.png")); // NOI18N
        menuItemSumaEscalar.setText("Suma Escalar");
        menuOperaciones.add(menuItemSumaEscalar);

        menuItemRestaEscalar.setIcon(new javax.swing.ImageIcon("/Users/joshtin_pc/Documents/Imagenes para proyecto/icons/resta.png")); // NOI18N
        menuItemRestaEscalar.setText("Resta Escalar");
        menuOperaciones.add(menuItemRestaEscalar);

        menuItemReflexionX.setIcon(new javax.swing.ImageIcon("/Users/joshtin_pc/Documents/Imagenes para proyecto/icons/reflexion x.png")); // NOI18N
        menuItemReflexionX.setText("Reflexion X");
        menuOperaciones.add(menuItemReflexionX);

        menuItemReflexionY.setIcon(new javax.swing.ImageIcon("/Users/joshtin_pc/Documents/Imagenes para proyecto/icons/reflexion Y.png")); // NOI18N
        menuItemReflexionY.setText("Reflexion Y");
        menuOperaciones.add(menuItemReflexionY);

        menuItemSuma.setIcon(new javax.swing.ImageIcon("/Users/joshtin_pc/Documents/Imagenes para proyecto/icons/suma.png")); // NOI18N
        menuItemSuma.setText("Suma");
        menuItemSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSumaActionPerformed(evt);
            }
        });
        menuOperaciones.add(menuItemSuma);

        menuItemResta.setIcon(new javax.swing.ImageIcon("/Users/joshtin_pc/Documents/Imagenes para proyecto/icons/resta.png")); // NOI18N
        menuItemResta.setText("Resta");
        menuOperaciones.add(menuItemResta);

        jMenuLogica.setIcon(new javax.swing.ImageIcon("/Users/joshtin_pc/Documents/Imagenes para proyecto/icons/Lógica.png")); // NOI18N
        jMenuLogica.setText("Lógica");

        jMenuItemAnd.setIcon(new javax.swing.ImageIcon("/Users/joshtin_pc/Documents/Imagenes para proyecto/icons/and.png")); // NOI18N
        jMenuItemAnd.setText("AND");
        jMenuItemAnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAndActionPerformed(evt);
            }
        });
        jMenuLogica.add(jMenuItemAnd);

        jMenuItemOr.setIcon(new javax.swing.ImageIcon("/Users/joshtin_pc/Documents/Imagenes para proyecto/icons/or.png")); // NOI18N
        jMenuItemOr.setText("OR");
        jMenuLogica.add(jMenuItemOr);

        jMenuItemNot.setIcon(new javax.swing.ImageIcon("/Users/joshtin_pc/Documents/Imagenes para proyecto/icons/not.png")); // NOI18N
        jMenuItemNot.setText("NOT");
        jMenuLogica.add(jMenuItemNot);

        jMenuItemXor.setIcon(new javax.swing.ImageIcon("/Users/joshtin_pc/Documents/Imagenes para proyecto/icons/xor.png")); // NOI18N
        jMenuItemXor.setText("XOR");
        jMenuLogica.add(jMenuItemXor);

        menuOperaciones.add(jMenuLogica);

        jMenuBar1.add(menuOperaciones);

        menFil.setText("Filtros");

        menuItemUm.setIcon(new javax.swing.ImageIcon("/Users/joshtin_pc/Documents/Imagenes para proyecto/icons/Umbralizacion.png")); // NOI18N
        menuItemUm.setText("Umbralización");
        menuItemUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemUmActionPerformed(evt);
            }
        });
        menFil.add(menuItemUm);

        menuItemCon.setIcon(new javax.swing.ImageIcon("/Users/joshtin_pc/Documents/Imagenes para proyecto/icons/Convolucion.png")); // NOI18N
        menuItemCon.setText("Convolución");
        menuItemCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConActionPerformed(evt);
            }
        });
        menFil.add(menuItemCon);

        jMenuBar1.add(menFil);

        jMenu3.setText("Ruido");

        jMenuAritmetica.setText("Media aritmetica");
        jMenuAritmetica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAritmeticaActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuAritmetica);

        jMenuMediaG.setText("Media geometrica");
        jMenuMediaG.setToolTipText("");
        jMenu3.add(jMenuMediaG);

        jMenuContra.setText("Media contra-armonica");
        jMenuContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuContraActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuContra);

        jMenuItemMediana.setText("Mediana");
        jMenuItemMediana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMedianaActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemMediana);

        jMenuMax.setText("Maximo");
        jMenuMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMaxActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuMax);

        jMenuMinimo.setText("Minimo");
        jMenu3.add(jMenuMinimo);

        jMenuMedio.setText("Medio");
        jMenuMedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMedioActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuMedio);

        jMenuAdaptativo.setText("Media Adaptativa");
        jMenu3.add(jMenuAdaptativo);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Espectro");

        jMenuTransformar.setText("Transformar");
        jMenu4.add(jMenuTransformar);

        jMenuEspectro.setText("Ver Espectro");
        jMenu4.add(jMenuEspectro);

        jMenu5.setText("Low Pass Filtering");

        jMenuILPF.setText("Ideal low pass filter");
        jMenuILPF.setToolTipText("");
        jMenu5.add(jMenuILPF);

        jMenuBLPF.setText("Butterworth low pass filter");
        jMenu5.add(jMenuBLPF);

        jMenu4.add(jMenu5);

        jMenu7.setText("High Pass Filtering");

        jMenuIHPF.setText("Ideal high pass filter");
        jMenu7.add(jMenuIHPF);

        jMenuBHPF.setText("Butterworth high pass filter");
        jMenu7.add(jMenuBHPF);

        jMenu4.add(jMenu7);

        jMenu8.setText("Ideal Band Filter");

        jMenuIBPF.setText("Ideal Band Pass Filter");
        jMenu8.add(jMenuIBPF);

        jMenuIBSF.setText("Ideal Band Stop Filter");
        jMenu8.add(jMenuIBSF);

        jMenu4.add(jMenu8);

        jMenu9.setText("Butterworth Band Filter");

        jMenuBBPF.setText("Butterworth Band Pass Filter");
        jMenu9.add(jMenuBBPF);

        jMenuBBSF.setText("Butterworth Band Stop Filter");
        jMenu9.add(jMenuBBSF);

        jMenu4.add(jMenu9);

        jMenuBar1.add(jMenu4);

        jMenu10.setText("Histograma");

        jMenuCalcularHistograma.setIcon(new javax.swing.ImageIcon("/Users/joshtin_pc/Documents/Imagenes para proyecto/icons/calcular.png")); // NOI18N
        jMenuCalcularHistograma.setText("Calcular Histograma");
        jMenuCalcularHistograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCalcularHistogramaActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuCalcularHistograma);

        jMenuVerHistograma.setIcon(new javax.swing.ImageIcon("/Users/joshtin_pc/Documents/Imagenes para proyecto/icons/Histograma.png")); // NOI18N
        jMenuVerHistograma.setText("Ver Histograma");
        jMenu10.add(jMenuVerHistograma);

        jMenuBar1.add(jMenu10);

        jMenu11.setText("Conversion de colores");

        jMenuRtoC.setIcon(new javax.swing.ImageIcon("/Users/joshtin_pc/Documents/Imagenes para proyecto/icons/RGB.png")); // NOI18N
        jMenuRtoC.setText("RGB a CMY");
        jMenuRtoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRtoCActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuRtoC);

        jMenuCtoR.setIcon(new javax.swing.ImageIcon("/Users/joshtin_pc/Documents/Imagenes para proyecto/icons/CMY.png")); // NOI18N
        jMenuCtoR.setText("CMY a RGB");
        jMenu11.add(jMenuCtoR);

        jMenuRtoH.setIcon(new javax.swing.ImageIcon("/Users/joshtin_pc/Documents/Imagenes para proyecto/icons/HSI.png")); // NOI18N
        jMenuRtoH.setText("RGB a HSI");
        jMenu11.add(jMenuRtoH);

        jMenuBar1.add(jMenu11);

        jMenu6.setText("Morfologícas");

        jManuDilatacion.setIcon(new javax.swing.ImageIcon("/Users/joshtin_pc/Documents/Imagenes para proyecto/icons/Dilatación.png")); // NOI18N
        jManuDilatacion.setText("Dilatacion");
        jMenu6.add(jManuDilatacion);

        jMenuErosion.setIcon(new javax.swing.ImageIcon("/Users/joshtin_pc/Documents/Imagenes para proyecto/icons/Erosión.png")); // NOI18N
        jMenuErosion.setText("Erosión");
        jMenuErosion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuErosionActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuErosion);

        jMenuApertura.setIcon(new javax.swing.ImageIcon("/Users/joshtin_pc/Documents/Imagenes para proyecto/icons/Apertura.png")); // NOI18N
        jMenuApertura.setText("Apertura");
        jMenu6.add(jMenuApertura);

        jMenuCierre.setIcon(new javax.swing.ImageIcon("/Users/joshtin_pc/Documents/Imagenes para proyecto/icons/Cierre.png")); // NOI18N
        jMenuCierre.setText("Cierre");
        jMenu6.add(jMenuCierre);

        jMenuBar1.add(jMenu6);

        jMenu2.setText("Ver");

        menuItemOriginal.setIcon(new javax.swing.ImageIcon("/Users/joshtin_pc/Documents/Imagenes para proyecto/icons/original.png")); // NOI18N
        menuItemOriginal.setText("Original");
        jMenu2.add(menuItemOriginal);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemRotar90ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRotar90ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemRotar90ActionPerformed

    private void menuItemSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSumaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemSumaActionPerformed

    private void menuItemUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemUmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemUmActionPerformed

    private void jMenuItemAndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemAndActionPerformed

    private void menuItemConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemConActionPerformed

    private void jMenuAritmeticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAritmeticaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuAritmeticaActionPerformed

    private void jMenuContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuContraActionPerformed

    private void jMenuItemMedianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMedianaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemMedianaActionPerformed

    private void jMenuMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuMaxActionPerformed

    private void jMenuMedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMedioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuMedioActionPerformed

    private void jMenuErosionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuErosionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuErosionActionPerformed

    private void jMenuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuGuardarActionPerformed

    private void jMenuCalcularHistogramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCalcularHistogramaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuCalcularHistogramaActionPerformed

    private void jMenuRtoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRtoCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuRtoCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem jManuDilatacion;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    public javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    public javax.swing.JMenuItem jMenuAdaptativo;
    public javax.swing.JMenuItem jMenuApertura;
    public javax.swing.JMenuItem jMenuAritmetica;
    public javax.swing.JMenuItem jMenuBBPF;
    public javax.swing.JMenuItem jMenuBBSF;
    public javax.swing.JMenuItem jMenuBHPF;
    public javax.swing.JMenuItem jMenuBLPF;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuCalcularHistograma;
    public javax.swing.JMenuItem jMenuCierre;
    public javax.swing.JMenuItem jMenuContra;
    public javax.swing.JMenuItem jMenuCreditos;
    public javax.swing.JMenuItem jMenuCtoR;
    public javax.swing.JMenuItem jMenuErosion;
    public javax.swing.JMenuItem jMenuEspectro;
    public javax.swing.JMenuItem jMenuGuardar;
    public javax.swing.JMenuItem jMenuIBPF;
    public javax.swing.JMenuItem jMenuIBSF;
    public javax.swing.JMenuItem jMenuIHPF;
    public javax.swing.JMenuItem jMenuILPF;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    public javax.swing.JMenuItem jMenuItemAnd;
    public javax.swing.JMenuItem jMenuItemMediana;
    public javax.swing.JMenuItem jMenuItemNot;
    public javax.swing.JMenuItem jMenuItemOr;
    public javax.swing.JMenuItem jMenuItemXor;
    private javax.swing.JMenu jMenuLogica;
    public javax.swing.JMenuItem jMenuMax;
    public javax.swing.JMenuItem jMenuMediaG;
    public javax.swing.JMenuItem jMenuMedio;
    public javax.swing.JMenuItem jMenuMinimo;
    public javax.swing.JMenuItem jMenuRtoC;
    public javax.swing.JMenuItem jMenuRtoH;
    public javax.swing.JMenuItem jMenuTransformar;
    public javax.swing.JMenuItem jMenuVerHistograma;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel labelImagen;
    public javax.swing.JMenu menFil;
    public javax.swing.JMenuItem menuItem180;
    public javax.swing.JMenuItem menuItem270;
    public javax.swing.JMenuItem menuItemAbrir;
    public javax.swing.JMenuItem menuItemCon;
    public javax.swing.JMenuItem menuItemEscalaGrises;
    public javax.swing.JMenuItem menuItemOriginal;
    public javax.swing.JMenuItem menuItemReflexionX;
    public javax.swing.JMenuItem menuItemReflexionY;
    public javax.swing.JMenuItem menuItemResta;
    public javax.swing.JMenuItem menuItemRestaEscalar;
    public javax.swing.JMenuItem menuItemRotar90;
    public javax.swing.JMenuItem menuItemSuma;
    public javax.swing.JMenuItem menuItemSumaEscalar;
    public javax.swing.JMenuItem menuItemTraslacion;
    public javax.swing.JMenuItem menuItemUm;
    public javax.swing.JMenu menuOperaciones;
    // End of variables declaration//GEN-END:variables
}
